# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fd5b6f0c90c6a7c9c8fe479acb7f926"
name = "theme-app-test-project"
handle = "theme-app-test-project"
application_url = "https://lose-to-pledge-resume.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lars-shop-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lose-to-pledge-resume.trycloudflare.com/auth/callback",
  "https://lose-to-pledge-resume.trycloudflare.com/auth/shopify/callback",
  "https://lose-to-pledge-resume.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
